fe/config/routes.rb
Judge::Application.routes.draw do
  resources :states

  resources :details

  resources :results

  resources :contest_tasks

  resources :tasks

  resources :contests

  get "/results/:id/my.json" => "results#my"
  get "/results/:id/t/:serial" => "results#show_task"

  post "/contest/:id/submit" => "contests#submit"
  get "/contests/:id/ranking" => "contests#ranking"

  get "/contests/:id/score" => "contests#score"

  get "contest_tasks/:id/:serial" => "contest_tasks#task"

  get "/judge" => "judge#index"
  get "/judge/:id" => "judge#tasks"
  get "/judge/:id/t/:serial" => "judge#task"
  get "/judge/:id/submit" => "judge#submit"
  get "/judge/:id/submittion" => "judge#submittion"
  get "/judge/:id/submittion/t/:serial" => "judge#task_submittion"
  get "/judge/:id/my" => "judge#my"
  get "/judge/:id/detail/:result_id" => "judge#detail"
  get "/judge/:id/ranking" => "judge#ranking"

  resource :login
  resource :logout

end

fe/app/models/contest_task.rb
class ContestTask < ActiveRecord::Base
  attr_accessible :contest_id, :serial, :task_id
  belongs_to :contest
  belongs_to :task
  validates :contest_id, :numericality => {:only_integer=>true}
  validates :task_id, :numericality => {:only_integer=>true}
  validates :key, :uniqueness => true

  validate 
end

fe/app/controllers/contest_tasks_controller.rb
class ContestTasksController < ApplicationController
  # GET /contest_tasks
  # GET /contest_tasks.json
  def index
    @contest_tasks = ContestTask
      .select("Contest_tasks.id,contest_id,task_id,serial,name,tle,mle")
      .where(contest_id:params[:contest_id])
      .joins(:task)
      .order("serial")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contest_tasks }
      format.xml  { render xml:  @contest_tasks }
    end
  end

  # GET /contest_tasks/1
  # GET /contest_tasks/1.json
  def show
    @contest_task = ContestTask.find(params[:id])
#    @task = ContestTask.find(params[:id])
#      .select("contest_id,task_id,serial,body,judge_type,mle,name,tle")
#      .where(contest_id:params[:id],serial:params[:serial])
#      .joins(:task).first

#    render :action => "../tasks/show"
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contest_task }
    end
  end

  def task
    if (contest_not_begin params[:id]) && !session[:admin]
      render :json => []
      return
    end
    @task = ContestTask.select("contest_id,task_id,serial,body,judge_type,mle,name,tle")
      .where(contest_id:params[:id],serial:params[:serial])
      .joins(:task).first
    render :json => @task
  end

  def score
    ct = ContestTask.where(params[:id])
    ret = {}
    ct.each{|c|
      t = Task.find(c.task_id)
      i = Input.where(:task_id=>t).sum(:score)
      ret[c.serial] = i
    }
    respond_to do |format|
      format.json { render json: ret }
      format.xml  { render xml: ret }
    end
  end

  # GET /contest_tasks/new
  # GET /contest_tasks/new.json
  def new
    @contest_task = ContestTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contest_task }
    end
  end

  # GET /contest_tasks/1/edit
  def edit
    @contest_task = ContestTask.find(params[:id])
  end

  # POST /contest_tasks
  # POST /contest_tasks.json
  def create
    @contest_task = ContestTask.new(params[:contest_task])
    @contest_task.key = @contest_task.contest_id.to_s+"_"+@contest_task.serial.to_s

    respond_to do |format|
      if @contest_task.save
        format.html { redirect_to @contest_task, notice: 'Contest task was successfully created.' }
        format.json { render json: @contest_task, status: :created, location: @contest_task }
      else
        format.html { render action: "new" }
        format.json { render json: @contest_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contest_tasks/1
  # PUT /contest_tasks/1.json
  def update
    @contest_task = ContestTask.find(params[:id])

    respond_to do |format|
      if @contest_task.update_attributes(params[:contest_task])
        format.html { redirect_to @contest_task, notice: 'Contest task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contest_tasks/1
  # DELETE /contest_tasks/1.json
  def destroy
    @contest_task = ContestTask.find(params[:id])
    @contest_task.destroy

    respond_to do |format|
      format.html { redirect_to contest_tasks_url }
      format.json { head :no_content }
    end
  end
end

fe/app/helpers/contest_tasks_helper.rb
module ContestTasksHelper
end

fe/app/views/contest_tasks/_form.html.erb
<%= form_for(@contest_task) do |f| %>
  <% if @contest_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest_task.errors.count, "error") %> prohibited this contest_task from being saved:</h2>

      <ul>
      <% @contest_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contest_id %><br />
    <%= f.number_field :contest_id %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :serial %><br />
    <%= f.text_field :serial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fe/app/views/contest_tasks/edit.html.erb
<h1>Editing contest_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest_task %> |
<%= link_to 'Back', contest_tasks_path %>

fe/app/views/contest_tasks/index.html.erb
<h1>Listing contest_tasks</h1>

<table>
  <tr>
    <th>Contest</th>
    <th>Task</th>
    <th>Serial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contest_tasks.each do |contest_task| %>
  <tr>
    <td><%= contest_task.contest_id %></td>
    <td><%= contest_task.task_id %></td>
    <td><%= contest_task.serial %></td>
    <td><%= link_to 'Show', contest_task %></td>
    <td><%= link_to 'Edit', edit_contest_task_path(contest_task) %></td>
    <td><%= link_to 'Destroy', contest_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contest task', new_contest_task_path %>

fe/app/views/contest_tasks/new.html.erb
<h1>New contest_task</h1>

<%= render 'form' %>

<%= link_to 'Back', contest_tasks_path %>

fe/app/views/contest_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contest:</b>
  <%= @contest_task.contest_id %>
</p>

<p>
  <b>Task:</b>
  <%= @contest_task.task_id %>
</p>

<p>
  <b>Serial:</b>
  <%= @contest_task.serial %>
</p>

<p>
  <b>Key:</b>
  <%= @contest_task.key %>
</p>


<%= link_to 'Edit', edit_contest_task_path(@contest_task) %> |
<%= link_to 'Back', contest_tasks_path %>