fe/config/routes.rb
Judge::Application.routes.draw do
  resources :states

  resources :details

  resources :results

  resources :contest_tasks

  resources :tasks

  resources :contests

  get "/results/:id/my.json" => "results#my"
  get "/results/:id/t/:serial" => "results#show_task"

  post "/contest/:id/submit" => "contests#submit"
  get "/contests/:id/ranking" => "contests#ranking"

  get "/contests/:id/score" => "contests#score"

  get "contest_tasks/:id/:serial" => "contest_tasks#task"

  get "/judge" => "judge#index"
  get "/judge/:id" => "judge#tasks"
  get "/judge/:id/t/:serial" => "judge#task"
  get "/judge/:id/submit" => "judge#submit"
  get "/judge/:id/submittion" => "judge#submittion"
  get "/judge/:id/submittion/t/:serial" => "judge#task_submittion"
  get "/judge/:id/my" => "judge#my"
  get "/judge/:id/detail/:result_id" => "judge#detail"
  get "/judge/:id/ranking" => "judge#ranking"

  resource :login
  resource :logout

end

fe/app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :state_name
  has_many :details
  has_many :results
#  belongs_to :result
end

fe/app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

fe/app/helpers/states_helper.rb
module StatesHelper
end

fe/app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fe/app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

fe/app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <tr>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= state.state %></td>
    <td><%= link_to 'Show', state %></td>
    <td><%= link_to 'Edit', edit_state_path(state) %></td>
    <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New State', new_state_path %>

fe/app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

fe/app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
  <%= @state.state %>
</p>


<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>