fe/config/routes.rb
Judge::Application.routes.draw do
  resources :states

  resources :details

  resources :results

  resources :contest_tasks

  resources :tasks

  resources :contests

  get "/results/:id/my.json" => "results#my"
  get "/results/:id/t/:serial" => "results#show_task"

  post "/contest/:id/submit" => "contests#submit"
  get "/contests/:id/ranking" => "contests#ranking"

  get "/contests/:id/score" => "contests#score"

  get "contest_tasks/:id/:serial" => "contest_tasks#task"

  get "/judge" => "judge#index"
  get "/judge/:id" => "judge#tasks"
  get "/judge/:id/t/:serial" => "judge#task"
  get "/judge/:id/submit" => "judge#submit"
  get "/judge/:id/submittion" => "judge#submittion"
  get "/judge/:id/submittion/t/:serial" => "judge#task_submittion"
  get "/judge/:id/my" => "judge#my"
  get "/judge/:id/detail/:result_id" => "judge#detail"
  get "/judge/:id/ranking" => "judge#ranking"

  resource :login
  resource :logout

end

fe/app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :contest_id, :contest_task_id, :lang_id, :message, :state_id, :user_id, :score
  belongs_to :contest_task
  belongs_to :user
  belongs_to :state
  has_many :details
end

fe/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  NUM = 30
  def show
    cont = Contest.find(params[:id])
    @result = Result
      .select("Results.id,state_id,Results.contest_id,lang_id,contest_task_id,score,Results.created_at,state_name,Tasks.name as task_name,task_id,user_id,Users.name as user_name,serial")
      .where(["Results.created_at >= ?",cont.begin])
      .where(:contest_id=>params[:id])
      .joins(:state)
      .joins(:contest_task => :task)
      .joins(:user)
      .order("Results.id DESC")
#      .joins(:state)
#      .joins(:contest_task => :task)
#      .joins(:user)
#      .offset(params[:offset].to_i*NUM)
#      .limit(NUM)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  def show_task
    cont = Contest.find(params[:id])
    serial = params[:serial]
    @result = Result
      .select("Results.id,state_id,Results.contest_id,lang_id,contest_task_id,score,Results.created_at,state_name,Tasks.name as task_name,task_id,user_id,Users.name as user_name,serial")
      .where(["Results.created_at >= ?",cont.begin])
      .where(:contest_id=>params[:id])
      .joins(:state)
      .joins(:contest_task => :task)
      .where(:contest_task_id => ContestTask.where(:contest_id=>cont.id,:serial=>serial).first.id)
      .joins(:user)
      .order("Results.id DESC")
#      .joins(:state)
#      .joins(:contest_task => :task)
#      .joins(:user)
#      .offset(params[:offset].to_i*NUM)
#      .limit(NUM)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end

  end

  def my
    @result = Result
      .select("Results.id,state_id,Results.contest_id,lang_id,contest_task_id,score,Results.created_at,state_name,Tasks.name as task_name,task_id,user_id,Users.name as user_name,serial")
      .where(:contest_id=>params[:id])
      .joins(:state)
      .joins(:contest_task => :task)
      .joins(:user)
      .where(:user_id => session[:user_id])
      .order("Results.id DESC")
    render json: @result;
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

fe/app/helpers/results_helper.rb
module ResultsHelper
end

fe/app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lang_id %><br />
    <%= f.number_field :lang_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label :contest_task_id %><br />
    <%= f.number_field :contest_task_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contest_id %><br />
    <%= f.number_field :contest_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fe/app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

fe/app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Lang</th>
    <th>Message</th>
    <th>State</th>
    <th>Contest task</th>
    <th>User</th>
    <th>Contest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.lang_id %></td>
    <td><%= result.message %></td>
    <td><%= result.state %></td>
    <td><%= result.contest_task_id %></td>
    <td><%= result.user_id %></td>
    <td><%= result.contest_id %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

fe/app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

fe/app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lang:</b>
  <%= @result.lang_id %>
</p>

<p>
  <b>Message:</b>
  <%= @result.message %>
</p>

<p>
  <b>State:</b>
  <%= @result.state %>
</p>

<p>
  <b>Contest task:</b>
  <%= @result.contest_task_id %>
</p>

<p>
  <b>User:</b>
  <%= @result.user_id %>
</p>

<p>
  <b>Contest:</b>
  <%= @result.contest_id %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>