fe/config/routes.rb
Judge::Application.routes.draw do
  resources :states

  resources :details

  resources :results

  resources :contest_tasks

  resources :tasks

  resources :contests

  get "/results/:id/my.json" => "results#my"
  get "/results/:id/t/:serial" => "results#show_task"

  post "/contest/:id/submit" => "contests#submit"
  get "/contests/:id/ranking" => "contests#ranking"

  get "/contests/:id/score" => "contests#score"

  get "contest_tasks/:id/:serial" => "contest_tasks#task"

  get "/judge" => "judge#index"
  get "/judge/:id" => "judge#tasks"
  get "/judge/:id/t/:serial" => "judge#task"
  get "/judge/:id/submit" => "judge#submit"
  get "/judge/:id/submittion" => "judge#submittion"
  get "/judge/:id/submittion/t/:serial" => "judge#task_submittion"
  get "/judge/:id/my" => "judge#my"
  get "/judge/:id/detail/:result_id" => "judge#detail"
  get "/judge/:id/ranking" => "judge#ranking"

  resource :login
  resource :logout

end

fe/app/models/detail.rb
class Detail < ActiveRecord::Base
  attr_accessible :input, :memory, :output, :result_id, :state, :time
  belongs_to :result
  belongs_to :state
end

fe/app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @result_id = params[:id]
#    contest_id = Result.find(@result_id).contest_id
    @result = Result
      .select("Results.id,state_id,Results.contest_id,serial,contest_task_id,task_id,score,Tasks.name as task_name,lang_id,user_id,Users.name as user_name,Results.created_at,state_name,message")
      .joins(:state)
      .joins(:contest_task => :task)
      .joins(:user)
      .find(@result_id)
#contest_not_end ? .where(:user_id=>session[:user_id]) : .all
    if !contest_end(@result.contest_id) && @result.user_id!=session[:user_id] && !session[:admin]
      render json: {}
      return
    end
    @details = Detail
      .select("result_id,state_id,output,input,state_name,time,memory")
      .where(:result_id=>@result_id).joins(:state)
    @code = ""
    @code = File.open("task_data/contests/#{@result.contest_id}/#{@result.id}_#{@result.user_id}_#{@result.contest_task_id}/Main."+(@result.lang_id==1 ? "c":"cpp")).read

#    @detail = Detail.find(params[:id])

    respond_to do |format|
#      format.html # show.html.erb
      format.json { render json: {:result=>@result,:code=>@code,:details=>@details} }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :no_content }
    end
  end
end

fe/app/helpers/details_helper.rb
module DetailsHelper
end

fe/app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :memory %><br />
    <%= f.number_field :memory %>
  </div>
  <div class="field">
    <%= f.label :result_id %><br />
    <%= f.number_field :result_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :input %><br />
    <%= f.text_field :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br />
    <%= f.text_field :output %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fe/app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

fe/app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <tr>
    <th>Memory</th>
    <th>Result</th>
    <th>State</th>
    <th>Time</th>
    <th>Input</th>
    <th>Output</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.memory %></td>
    <td><%= detail.result_id %></td>
    <td><%= detail.state %></td>
    <td><%= detail.time %></td>
    <td><%= detail.input %></td>
    <td><%= detail.output %></td>
    <td><%= link_to 'Show', detail %></td>
    <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
    <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Detail', new_detail_path %>

fe/app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

fe/app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Memory:</b>
  <%= @detail.memory %>
</p>

<p>
  <b>Result:</b>
  <%= @detail.result_id %>
</p>

<p>
  <b>State:</b>
  <%= @detail.state %>
</p>

<p>
  <b>Time:</b>
  <%= @detail.time %>
</p>

<p>
  <b>Input:</b>
  <%= @detail.input %>
</p>

<p>
  <b>Output:</b>
  <%= @detail.output %>
</p>


<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>